version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_backend
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    environment:
      DB_HOST: aws-0-eu-west-3.pooler.supabase.com
      DB_PORT: 6543
      DB_USER: postgres.mxvqxeylelrehqjwbxmx
      DB_PASSWORD: BiteFinderlithop21
      DB_NAME: postgres
    volumes:
      - ./backend:/app

networks:
  mynetwork:
    driver: bridge
